name = "sommark"
grammar = "markdown"
path_suffixes = ["smark"]
language_servers = ["sommark-lsp"]

line_comment = "#"
brackets = [
    { start = "[", end = "]", close = true, newline = true },
    { start = "${", end = "}$", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "@_", end = "_@", close = true, newline = false },
    { start = "###", end = " ###", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
    { start = "`", end = "`", close = true, newline = false }
]
